#####
# This Dockerfile is for development and testing purposes
# It is used to create an image from current locally checked out branch
#####

FROM golang:1.14
ENV AKAMAI_CLI_HOME=/cli
COPY . /go/src/github.com/akamai/cli
RUN /bin/bash -c 'mkdir /cli && \
    apt update && \
    apt install -y python-pip python3 python3-pip jq libssl-dev npm && \
    pip2 install --upgrade pip && \
    pip3 install --upgrade pip && \
    cd $GOPATH/src/github.com/akamai/cli && \
    go mod tidy && \
    go build -o akamai-master-linuxamd64 cli/main.go; \
    mv akamai-*-linuxamd64 /usr/local/bin/akamai && chmod +x /usr/local/bin/akamai && \
    mkdir -p /cli/.akamai-cli && \
    curl -A "" https://developer.akamai.com/cli/package-list.json | jq .packages[].name | sed s/\"//g | xargs akamai install --force'

RUN echo "[cli]" > /cli/.akamai-cli/config && \
    echo "cache-path            = /cli/.akamai-cli/cache" >> /cli/.akamai-cli/config && \
    echo "config-version        = 1" >> /cli/.akamai-cli/config && \
    echo "enable-cli-statistics = false" >> /cli/.akamai-cli/config && \
    echo "last-ping             = 2018-04-27T18:16:12Z" >> /cli/.akamai-cli/config && \
    echo "client-id             =" >> /cli/.akamai-cli/config && \
    echo "install-in-path       =" >> /cli/.akamai-cli/config && \
    echo "last-upgrade-check    = ignore" >> /cli/.akamai-cli/config

VOLUME /root/.edgerc
VOLUME /cli
ENTRYPOINT ["/usr/local/bin/akamai"]
CMD ["--daemon"]
